### ISSUE TITLE
New Node Component: Result Item Details - Gallery

### ISSUE THREAD

**Issue by pguhr** [Cognigy/Extensions#37]
# Related extension module
elastic-search

# Short description:
Present one result item in gallery view - means (at least) take a certain gallery layout and show the DocIcon

# Flow dependencies:

1. Requires Elastic-Search Node
2. Probably, requires Result List

Support for nested list elements required.

# Additional context

Related to available node types:
Similar to Say Node Output Type Gallery (?)

Reason for expected dependency to Result List Node is, that I expect we have to present a list first before we can select a single item.
Exception might be that we present only one certain item (e. g. the number one hit)

**Comment by AlexTeusz** [comment]
Hi @pguhr , 

In order to present the returned **hits** as gallery elements, I will create a **Show Results** Flow node in the extension. In general, one can use the following JSON format to send gallery elements (just for your information):

```js
		_cognigy: {
			_fallbackText: "A text that will be read out loud on voice channels.",
			_default: {
				message: {
					attachment: {
						type: 'template',
						payload: {
							template_type: 'generic',
							elements: ["list of": "elements"]
						}
					}
				}
			}
		}
```

Later, the **Cognigy API** can be used to send a gallery message using the SAY Node:
```js
api.output('', cognigyJSON);
```

**Comment by AlexTeusz** [comment]
The problem here is, that the Elastic Search result can be very different so that the elements that should be used for the gallery depend on the specific use case. 

Maybe it would be a more powerful solution if one just uses the [CODE](https://docs.cognigy.com/docs/code) Node in Cognigy with the example shown above.

**Comment by AlexTeusz** [comment]
Created feature branch:
https://github.com/Cognigy/Extensions/tree/feature/elastic-search-show-results
